name = "ReactionMechanismSimulator"
uuid = "c2d78dd2-25c4-5b79-bebc-be6c69dd440f"
authors = ["Matt Johnson <mjohnson541@gmail.com>"]
version = "0.4.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqSensitivity = "41bf760c-e81c-5289-8e54-58b1f1f8abe2"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
QuartzImageIO = "dca85d43-d64c-5e67-8c65-017450d5d020"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
SmoothingSplines = "102930c3-cf33-599f-b3b1-9a29a5acab30"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
CSV = "0.7,0.8, 0.9"
Calculus = "0.4,0.5"
Colors = "0.11,0.12"
Conda = "1"
DiffEqBase = "6"
DiffEqSensitivity = "6.22.0"
ForwardDiff = "0.10"
Images = "0.23"
IterTools = "1.3.0"
LsqFit = "0.12"
ModelingToolkit = "3"
OrdinaryDiffEq = "5"
Parameters = "0.12"
PyCall = "1"
PyPlot = "2"
QuartzImageIO = "0.7"
RecursiveArrayTools = "2.17"
ReverseDiff = "1.9"
SmoothingSplines = "0.2.1"
SpecialFunctions = "0.10"
StaticArrays = "0.12"
Sundials = "4"
Tracker = "0.2"
Unitful = "1.3.0"
YAML = "0.4"
Zygote = "0.5,0.6"
julia = "1.4"
