name = "ReactionMechanismSimulator"
uuid = "c2d78dd2-25c4-5b79-bebc-be6c69dd440f"
authors = ["Matt Johnson <mjohnson541@gmail.com>"]
version = "0.2.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
QuartzImageIO = "dca85d43-d64c-5e67-8c65-017450d5d020"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
julia = "1"
CSV = "0.7.3"
Calculus = "0.5.1"
Colors = "0.12.3"
Dierckx = "0.4.2"
DiffEqBase = "6.6.0"
ForwardDiff = "0.10.12"
Images = "<1"
IterTools = "1.3.0"
OrdinaryDiffEq = "5.0.0"
Parameters = "0.12.1"
PyCall = "1.91.4"
PyPlot = "2.9.0"
QuartzImageIO = "0.7.1"
SpecialFunctions = "<1"
StaticArrays = "0.12.4"
Sundials = "4.2.5"
Unitful = "1.3.0"
YAML = "0.4.0"
